name: recipe_book_app
description: A recipe book app for CSC 4360
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/toast.jpg
    - assets/images/cereal.jpg
    - assets/images/eggs.jpg
    - assets/images/sandwich.jpg